spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blockeeper?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: bosPoolName
      max-lifetime: 1800000

